/*
* generated by Xtext
*/
package ro.fii.wade.voces.contentassist;

import org.eclipse.emf.ecore.EObject;
import org.eclipse.jface.text.contentassist.ICompletionProposal;
import org.eclipse.xtext.Assignment;
import org.eclipse.xtext.ui.core.editor.contentassist.ContentAssistContext;
import org.eclipse.xtext.ui.core.editor.contentassist.ICompletionProposalAcceptor;

import ro.fii.wade.voces.contentassist.AbstractMetavocProposalProvider;
/**
 * see http://www.eclipse.org/Xtext/documentation/latest/xtext.html#contentAssist on how to customize content assistant
 */
public class MetavocProposalProvider extends AbstractMetavocProposalProvider {
	@Override
	public void completeNSElement_Name(EObject model, Assignment assignment,
			ContentAssistContext context, ICompletionProposalAcceptor acceptor) {
		// TODO Auto-generated method stub
		//super.completeNSElement_Name(model, assignment, context, acceptor);
		
		//attach here ns elements from WS
		String proposal = "dummy_NS_element";
		ICompletionProposal  completionProposal = createCompletionProposal(proposal, context);
		
		acceptor.accept(completionProposal);
	}
	
	@Override
	public void completeVocNS_Name(EObject model, Assignment assignment,
			ContentAssistContext context, ICompletionProposalAcceptor acceptor) {
		// TODO Auto-generated method stub
		//super.completeVocNS_Name(model, assignment, context, acceptor);
		
		//attach here ns name from WS
		String proposal = "dummy_NS";
		ICompletionProposal  completionProposal = createCompletionProposal(proposal, context);
		
		acceptor.accept(completionProposal);
	}
}
