/*
 * generated by Xtext
 */
package ro.fii.wade.voces;

/**
 * Use this class to register components to be used within the IDE.
 */
public class MetavocRuntimeModule extends ro.fii.wade.voces.AbstractMetavocRuntimeModule {

}
