/*
 * generated by Xtext
 */
package ro.fii.wade.voces;

/**
 * Use this class to register components to be used within the IDE.
 */
public class MetavocUiModule extends ro.fii.wade.voces.AbstractMetavocUiModule {

}
