/*
* generated by Xtext
*/
package ro.fii.wade.voces.outline;

import org.eclipse.xtext.ui.common.editor.outline.transformer.AbstractDeclarativeSemanticModelTransformer;

/**
 * customization of the default outline structure
 * 
 */
public class MetavocTransformer extends AbstractDeclarativeSemanticModelTransformer {
	
}
