/*
* generated by Xtext
*/
package ro.fii.wade.voces.parser.antlr;

import org.antlr.runtime.ANTLRInputStream;
import org.eclipse.xtext.parser.antlr.ITokenDefProvider;
import org.eclipse.xtext.parser.IParseResult;
import org.eclipse.xtext.parser.ParseException;
import org.eclipse.xtext.parser.antlr.XtextTokenStream;

import com.google.inject.Inject;

import ro.fii.wade.voces.services.MetavocGrammarAccess;

public class MetavocParser extends org.eclipse.xtext.parser.antlr.AbstractAntlrParser {
	
	@Inject 
    protected ITokenDefProvider antlrTokenDefProvider;
	
	@Inject
	private MetavocGrammarAccess grammarAccess;
	
	@Override
	protected IParseResult parse(String ruleName, ANTLRInputStream in) {
		ro.fii.wade.voces.parser.antlr.internal.InternalMetavocLexer lexer = new ro.fii.wade.voces.parser.antlr.internal.InternalMetavocLexer(in);
		XtextTokenStream stream = new XtextTokenStream(lexer, antlrTokenDefProvider);
		stream.setInitialHiddenTokens("RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT");
		ro.fii.wade.voces.parser.antlr.internal.InternalMetavocParser parser = new ro.fii.wade.voces.parser.antlr.internal.InternalMetavocParser(
				stream, getElementFactory(), grammarAccess);
		parser.setTokenTypeMap(antlrTokenDefProvider.getTokenDefMap());
		try {
			if(ruleName != null)
				return parser.parse(ruleName);
			return parser.parse();
		} catch (Exception re) {
			throw new ParseException(re.getMessage(),re);
		}
	}
	
	@Override 
	protected String getDefaultRuleName() {
		return "XMLModel";
	}
	
	public MetavocGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}
	
	public void setGrammarAccess(MetavocGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
}
